#!/usr/bin/env python3
"""Generate docs/ISSUE_BACKLOG.md from the backlog definitions and GitHub.

Reads every ``tools/backlog/*.json`` (except ``labels.json``), matches each
definition to its GitHub issue number by title, and writes a grouped manifest.

Requires the ``gh`` CLI to be authenticated. Read-only.
"""

from __future__ import annotations

import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKLOG = Path(__file__).resolve().parent / "backlog"
OUTPUT = ROOT / "docs" / "ISSUE_BACKLOG.md"

CATEGORY_PRIORITY = [
    "security",
    "ai",
    "soroban",
    "rust",
    "cli",
    "github",
    "ci",
    "testing",
    "performance",
    "documentation",
    "developer-experience",
]

PHASES = {
    f"phase-{n}": title
    for n, title in enumerate(
        [
            "Foundation and Architecture",
            "Source Parsing and Project Intelligence",
            "Security Analysis Engine",
            "Soroban Security Detectors",
            "Rule Quality and Research",
            "CLI and Reporting",
            "Baselines, Incremental Scanning and CI",
            "GitHub and Developer Integrations",
            "Developer Experience",
            "Advanced Analysis and Optional AI",
            "Production Hardening and Release",
        ],
        start=1,
    )
}


def gh_numbers() -> dict[str, int]:
    result = subprocess.run(
        ["gh", "issue", "list", "--state", "open", "--limit", "2000", "--json", "number,title"],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if result.returncode != 0:
        print("Failed to list issues:", result.stderr, file=sys.stderr)
        sys.exit(1)
    return {item["title"]: item["number"] for item in json.loads(result.stdout or "[]")}


def category(labels: list[str]) -> str:
    for candidate in CATEGORY_PRIORITY:
        if candidate in labels:
            return candidate
    return "general"


def short(text: str, limit: int = 110) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "\u2026"


def main() -> int:
    numbers = gh_numbers()
    issues = []
    skipped = []
    for path in sorted(BACKLOG.glob("*.json")):
        if path.name == "labels.json":
            continue
        for issue in json.loads(path.read_text(encoding="utf-8")):
            number = numbers.get(issue["title"])
            if number is None:
                # Definition no longer corresponds to an open issue
                # (completed or superseded by a split).
                skipped.append(issue["title"])
                continue
            labels = issue.get("labels", [])
            phases = [l for l in labels if l.startswith("phase-")]
            issues.append(
                {
                    "title": issue["title"],
                    "phase": phases[0] if phases else "phase-?",
                    "category": category(labels),
                    "difficulty": issue.get("complexity", "medium"),
                    "deps": issue.get("deps", "None."),
                    "problem": issue["problem"],
                    "number": number,
                }
            )

    issues.sort(key=lambda i: (i["phase"], i["number"] or 10**9))

    lines = [
        "# Issue Backlog",
        "",
        "The complete open contributor backlog. Generated by",
        "[`tools/generate_manifest.py`](../tools/generate_manifest.py) from",
        "`tools/backlog/*.json`; issue numbers are resolved from GitHub.",
        "Closed and superseded definitions are excluded.",
        "",
        f"**Total open issues:** {len(issues)}",
        "",
        "Complexity labels use `difficulty/trivial`, `difficulty/medium`, and",
        "`difficulty/high`. Dependencies are noted where order matters.",
        "",
    ]

    by_phase = defaultdict(list)
    for issue in issues:
        by_phase[issue["phase"]].append(issue)

    for phase in sorted(by_phase, key=lambda p: int(p.split("-")[1])):
        lines.append(f"## {phase} — {PHASES.get(phase, 'Other')}")
        lines.append("")
        lines.append("| # | Title | Category | Difficulty | Dependencies |")
        lines.append("| - | ----- | -------- | ---------- | ------------ |")
        for issue in by_phase[phase]:
            num = f"#{issue['number']}" if issue["number"] else "—"
            title = issue["title"].replace("|", "\\|")
            deps = issue["deps"].replace("|", "\\|")
            lines.append(
                f"| {num} | {title} | {issue['category']} | {issue['difficulty']} | {deps} |"
            )
        lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append("| Phase | Count |")
    lines.append("| ----- | ----- |")
    for phase in sorted(by_phase, key=lambda p: int(p.split("-")[1])):
        lines.append(f"| {phase} | {len(by_phase[phase])} |")
    lines.append(f"| **Total** | **{len(issues)}** |")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT} with {len(issues)} open issues.")
    if skipped:
        print(f"Excluded {len(skipped)} closed/superseded definition(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
